### ISSUE TITLE
nixos-18.09 compatibility

### ISSUE THREAD

**Issue by zimbatm** [colemickens/nixpkgs-wayland#5]
Is there any interest in having the overlay work with 18.09?

So far these are the issues that I found:
* fmt isn't packaged
* wayland-protocols is too old
* meson probably needs to be upgraded too

**Comment by colemickens** [comment]
Did the channel advance today and `wayland-protocols` update, or am I crazy?

I had seen this earlier, but now it seems to be working?

The things that need newer `meson` are already using `meson480` since the upstream PR in nixpkgs is still in progress. I learned of this from the upstream PR that did this for wlroots and I've copied it into at least one other package in here.

Can you spot check the commit https://github.com/colemickens/nixpkgs-wayland/commit/0decdd088f2fecfa892dffdd1e529e66c8e0bf33 and see if it looks okay? And/or try deleting from the store and pulling from the cache and seeing if it works? (I assume you have an 18.09 system?)

**Comment by colemickens** [comment]
never mind, found a bug in `update.sh`, will update soon.

**Comment by bbigras** [comment]
Should this issue be closed now that 18.09 is not supported anymore (since 57370790c7afa85bd06c73607ccfeda9329c1234)?

**Comment by zimbatm** [comment]
thanks @bbigras
