### ISSUE TITLE
add way-cooler

### ISSUE THREAD

**Issue by ookhoi** [colemickens/nixpkgs-wayland#6]
Would it make sense to add https://github.com/way-cooler/way-cooler ?

**Comment by colemickens** [comment]
Yeah, [I would like to add it](https://github.com/colemickens/nixpkgs-wayland/blob/84b0e7d8f70e683e6ffe1686d7d28cad8138eaec/update.sh#L59).

Just haven't done it yet, since it looks a bit more involved than some of the other packages, possibly.

(I'd certainly merge it!)

**Comment by colemickens** [comment]
It looks like `way-cooler` is currently using a `way-cooler.nix` file that was manually generated with `carnix` rather than with `buildRustPackage`.

It might be worth seeing if we can build `way-cooler` with `buildRustPackage` instead, but it might not, there's a lot of machinery in the nix files for that package. If not, then there will need to be an `way-cooler/update.sh` that can call `carnix` appropriately, and a `shell.nix` to go with it for ensure `carnix` is available. PRs welcome for either solution.

Additionally, `way-cooler` is currently broken on `nixos-unstable` (though this may be fixed with a newer version of it)...

**Comment by colemickens** [comment]
there's a wip pr here: https://github.com/colemickens/nixpkgs-wayland/pull/19

**Comment by bnjmnt4n** [comment]
This can also probably be closed, since way-cooler has since been archived (http://way-cooler.org/blog/2020/01/09/way-cooler-post-mortem.html) :cry:
